<a href="https://colab.research.google.com/github/alexsandrors91/Cientista_de_dados/blob/master/Aula2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **AULA 2 - Manipulação com *arrays* Numpy**

---

> Alterando o formato de uma matriz...



```
np.reshape()

np.newaxis()

```



In [1]:
# Importando a biblioteca

import numpy as np

In [2]:
# Criando uma nova array

a = np.arange(0,100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
# Consultando as dimensões

a.shape
a.ndim
a.size

100

In [3]:
# Alterando o formato de uma matriz

b = a.reshape(10,10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [7]:
# Consultando as dimensões

b.shape
#b.ndim
#b.size

(10, 10)

In [8]:
# Convertendo 1D array em 2D array

c = a[np.newaxis, :]
print(c)
c.shape

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]


(1, 100)

In [ ]:
# Consultando as dimensões

c.shape 
c.ndim
c.size

100

Para saber mais sobre manipulação de forma de arrays acesse: https://numpy.org/doc/stable/user/quickstart.html#quickstart-shape-manipulation

> Ordenando, juntando e dividindo matrizes...

```
np.flat  # Iterando os elementos da array

np.sort()  # Ordenando os elementos da array

np.concatenate()  # Juntando arrays

np.hstack()  # Juntando horizontalmente

np.vstack()  # Juntando verticalmente

np.hsplit()  # Dividindo arrays

```

In [9]:
# Criando uma nova array

d = np.array([5,7,8,6,1,10,16,18,50,24,25,89,100,63,41,22,28,33,35,0])
print(d)

[  5   7   8   6   1  10  16  18  50  24  25  89 100  63  41  22  28  33
  35   0]


In [10]:
# Iterando os elementos da array

for element in d.flat:
  print(element)

5
7
8
6
1
10
16
18
50
24
25
89
100
63
41
22
28
33
35
0


In [11]:
# Ordenando os elementos da array

d2 = np.sort(d)
print(d2)

[  0   1   5   6   7   8  10  16  18  22  24  25  28  33  35  41  50  63
  89 100]


In [12]:
# Iterando os elementos da array

for element in d2.flat:
  print(element)

0
1
5
6
7
8
10
16
18
22
24
25
28
33
35
41
50
63
89
100


Para saber mais ordenação de arrays acesse: https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort

In [ ]:
# Juntando arrays

e = np.array([2,3,4,5,6])
f = np.array([7,8,9,10,11])

ef = np.concatenate([e,f])

print(ef)
ef.shape # Consultando as dimensões

[ 2  3  4  5  6  7  8  9 10 11]


(10,)

In [ ]:
# Juntando arrays horizontalmente

ef2 = np.hstack((e,f))
print(ef2)
ef2.shape # Consultando as dimensões

[ 2  3  4  5  6  7  8  9 10 11]


(10,)

In [ ]:
# Juntando arrays verticalmente

ef3 = np.vstack((e,f))
print(ef3)
ef3.shape # Consultando as dimensões

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


(2, 5)

Para saber mais sobre a função `concatenate` acesse: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate

In [ ]:
# Dividindo arrays

ef4 = np.hsplit(ef, 5)
print(ef4)

[array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]), array([10, 11])]


In [ ]:
type(ef3)

numpy.ndarray

In [ ]:
type(ef4) # É uma lista de arrays

list

Para saber mais sobre junção e divisão de arrays acesse: https://numpy.org/doc/stable/user/quickstart.html#quickstart-stacking-arrays